[tool.flake8]
max-line-length = 140
exclude = ["venv", "__init__.py"]

[tool.black]
line-length = 110
exclude = ["venv", "__init__.py", "dupla_*"]

[tool.isort]
profile="black"
skip = ["venv", "__init__.py", "dupla_discal/*", "dupla_renderers/*", "dupla_tools/*"]